#2.3(вместо задачи 2)
my_list = ['в', '5', 'часов', '17', 'минут', 'температура', 'воздуха', 'была', '+5', 'градусов']
print(id(my_list))
my_list.insert(1, '"')
my_list.insert(3, '"')
my_list.insert(5, '"')
my_list.insert(7, '"')
my_list.insert(-1, '"')
my_list.insert(- 3, '"')
my_list[2] = my_list[2].replace("5", '05')
my_list[-3] = my_list[-3].replace("+5", '+05')
my_str = " ".join(my_list)
my_str = my_str.replace('" 05 "', '"05"')
my_str = my_str.replace('" 17 "', '"17"')
my_str = my_str.replace('" +05 "', '"+05"')

print(my_list)
print(id(my_list))
print(my_str)